EPMRPP-85619 || Create global integration for GitLab plugin
reportportal/plugin-bts-gitlab pull request #1
Opened 2023-10-12 08:45 UTC by Vadim73i

2023-10-12 11:42 UTC, AmsterGet requested changes

2023-10-12 11:42 UTC, AmsterGet commented on gradle.properties
> +version=23.3
All our plugins and services should follow semantic versioning.
So please use version 1.0.

2023-10-12 11:42 UTC, AmsterGet commented on project-properties.gradle
> +    publishRepo = "https://maven.pkg.github.com/reportportal/plugin-gitlab-epam"
What is the reason of this rename?

2023-10-12 11:42 UTC, AmsterGet commented on ui/README.md
> +# Plugin template for Epam Report Portal
Please update title.

2023-10-12 11:42 UTC, AmsterGet commented on ui/README.md
> +_Available only from RP v5.8_: use
Update required version to 23.3.

2023-10-12 11:42 UTC, AmsterGet commented on ui/package.json
> +    "rp"
We can extend it now and add 'gitlab', 'bts', 'plugin'.

2023-10-12 11:42 UTC, AmsterGet commented on ui/tsconfig.json
> +
What is the reason of adding all these aliases here?

2023-10-12 11:42 UTC, AmsterGet commented on ui/src/components/integrationSettings/integrationSettings.tsx
> +    lib: { useDispatch },
Please import `useDispatch` from `react-redux` lib.

2023-10-12 11:42 UTC, AmsterGet commented on ui/src/components/integrationFormFields/integrationFormFields.tsx
> +        name="apiToken"
Let's use field names as constants, especially if they used several times.

2023-10-12 15:01 UTC, AmsterGet requested changes

2023-10-13 08:08 UTC, Bam6ycha requested changes

2023-10-13 08:08 UTC, Bam6ycha commented on ui/src/components/integrationFormFields/integrationFormFields.tsx
> +import React, { FC, useEffect } from 'react';
Actually we do not need to import React here, it imports automatically in compilation time

2023-10-13 08:10 UTC, Bam6ycha commented
Also, I have a problem with .gitignore, it does not include node_modules

2023-10-13 11:57 UTC, Bam6ycha approved these changes

2023-10-13 11:58 UTC, Vadim73i commented
> Also, I have a problem with .gitignore, it does not include node_modules

ui/.gitignore includes "node_modules/"

2023-10-13 12:21 UTC, merged